; Joomla! Project
; (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

GUIDEDTOURS_JOOMLA_WHATSNEW_6_1="O que há de novo no Joomla 6.1"
GUIDEDTOURS_JOOMLA_WHATSNEW_6_1_DESCRIPTION="Descubra os novos recursos e melhorias no Joomla 6.1, incluindo o novo Workflow Graph, melhorias na mídia e muito mais."
