; Joomla! Project
; (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CAPTCHA_POW_CAPTCHA="Captcha - POW Captcha"
PLG_CAPTCHA_POWCAPTCHA_XML_DESCRIPTION="Este plugin CAPTCHA apresenta uma tarefa matemática ao navegador do usuário que o navegador pode resolver automaticamente. Não se destina a provar que o usuário é humano, mas sim provar que o usuário está disposto a investir o tempo necessário para resolver a tarefa. Atualmente baseado na biblioteca Altcha (altcha.org)."
PLG_CAPTCHA_POW_CAPTCHA_SITE_KEY_LABEL="Chave do Site"
PLG_CAPTCHA_POW_CAPTCHA_SITE_KEY_DESC="Insira a Chave do Site fornecida pelo painel do POW Captcha."
PLG_CAPTCHA_POW_CAPTCHA_SECRET_KEY_LABEL="Chave Secreta"
PLG_CAPTCHA_POW_CAPTCHA_SECRET_KEY_DESC="Insira a Chave Secreta fornecida pelo painel do POW Captcha."
PLG_CAPTCHA_POW_CAPTCHA_THEME_LABEL="Tema"
PLG_CAPTCHA_POW_CAPTCHA_THEME_DESC="Selecione o tema para o widget POW Captcha."
PLG_CAPTCHA_POW_CAPTCHA_THEME_AUTO="Automático"
PLG_CAPTCHA_POW_CAPTCHA_THEME_LIGHT="Claro"
PLG_CAPTCHA_POW_CAPTCHA_THEME_DARK="Escuro"
