; Joomla! Project
; (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_PRIVACYCONSENT="Tarefa - Verificação de Consentimento de Privacidade"
PLG_TASK_PRIVACYCONSENT_XML_DESCRIPTION="Esta tarefa verifica usuários que não consentiram com a política de privacidade e envia um lembrete."
PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_DESC="Número de dias após os quais o consentimento de privacidade expirará."
PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_LABEL="Expiração"
PLG_TASK_PRIVACYCONSENT_INVALIDATE_TITLE="Expiração de consentimentos de privacidade"
PLG_TASK_PRIVACYCONSENT_INVALIDATE_DESC="Gerenciar a expiração de consentimentos de privacidade"
PLG_TASK_PRIVACYCONSENT_EMAIL_REMIND_BODY="Seu consentimento de privacidade dado em {URL} expirará em alguns dias. Você pode renovar o consentimento de privacidade para este site.\n\nPara fazer isso, você pode completar uma das seguintes tarefas:\n\n1. Visite o seguinte URL: {TOKENURL}\n\n2. Copie seu token deste e-mail, visite a URL referenciada e cole seu token no formulário.\nURL: {FORMURL}\nToken: {TOKEN}\n\nObserve que este token é válido apenas para esta conta."
PLG_TASK_PRIVACYCONSENT_EMAIL_REMIND_SUBJECT="Consentimento de Privacidade em {SITENAME}"
PLG_TASK_PRIVACYCONSENT_LOG_REMIND_END="Fim do lembrete"
PLG_TASK_PRIVACYCONSENT_MAIL_REQUEST_REMINDER_DESC="Lembrete para renovar o consentimento de privacidade para este site."
PLG_TASK_PRIVACYCONSENT_MAIL_REQUEST_REMINDER_TITLE="Tarefa - Consentimento de Privacidade: Renovar Consentimento"
PLG_TASK_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_MESSAGE="O consentimento de privacidade expirou para %1$s."
PLG_TASK_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_SUBJECT="Consentimento de Privacidade Expirado"
PLG_TASK_PRIVACYCONSENT_REMINDBEFORE_DESC="Número de dias para enviar um lembrete antes da expiração do consentimento de privacidade."
PLG_TASK_PRIVACYCONSENT_REMINDBEFORE_LABEL="Lembrar"
