; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_MEDIA="Campos - Mídia"
PLG_FIELDS_MEDIA_LABEL="Mídia (%s)"
PLG_FIELDS_MEDIA_AUDIO_LABEL="Áudio (%s)"
PLG_FIELDS_MEDIA_DOCUMENT_LABEL="Documento (%s)"
PLG_FIELDS_MEDIA_VIDEO_LABEL="Vídeo (%s)"
PLG_FIELDS_MEDIA_PARAMS_DIRECTORY_LABEL="Diretório"
PLG_FIELDS_MEDIA_FIELD_MEDIA_EXTENSIONS_DESC="Extensões de mídia permitidas separadas por vírgula."
PLG_FIELDS_MEDIA_FIELD_MEDIA_EXTENSIONS_LABEL="Extensões de Mídia"
PLG_FIELDS_MEDIA_PARAMS_AUTOPLAY_LABEL="Reprodução automática"
PLG_FIELDS_MEDIA_PARAMS_CONTROLS_LABEL="Mostrar controles"
PLG_FIELDS_MEDIA_PARAMS_CSS_CLASS_LABEL="Classe CSS"
PLG_FIELDS_MEDIA_PARAMS_IMAGE_CLASS_LABEL="Classe de imagem"
PLG_FIELDS_MEDIA_PARAMS_LOOP_LABEL="Repetir reprodução"
PLG_FIELDS_MEDIA_PARAMS_MUTED_LABEL="Mudo"
PLG_FIELDS_MEDIA_PARAMS_PRELOAD_AUTO="Pré-carregar automaticamente"
PLG_FIELDS_MEDIA_PARAMS_PRELOAD_LABEL="Pré-carregar"
PLG_FIELDS_MEDIA_PARAMS_PRELOAD_METADATA="Apenas metadados"
PLG_FIELDS_MEDIA_PARAMS_PRELOAD_NONE="Nenhum"
PLG_FIELDS_MEDIA_PARAMS_PREVIEW_INLINE="Em linha"
PLG_FIELDS_MEDIA_PARAMS_PREVIEW_LABEL="Visualização"
PLG_FIELDS_MEDIA_PARAMS_VIDEO_PLAYSINLINE_LABEL="Reproduzir em linha"
PLG_FIELDS_MEDIA_PARAMS_VIDEO_POSTER_LABEL="Imagem do pôster"
PLG_FIELDS_MEDIA_XML_DESCRIPTION="Este plugin permite criar novos campos do tipo 'mídia' em qualquer extensão onde campos personalizados sejam suportados."
